version: "3.6"

services:
  ccip-resolver:
    image: dm3org/offchain-resolver:v0.0.2
    restart: always
    environment:
          SIGNER_PRIVATE_KEY: ${SIGNER_PRIVATE_KEY}
          CONFIG: '{"0x410ebbabb4471e9c18cc36642f4057812e125e94":{"type":"signing","handlerUrl":"http://host.docker.internal:8887"}}'
    ports:
    - "8081:8081"
        


