version: "3.6"

services:
    ens-data-source:
        image: dm3org/ens-bedrock-resolver:v0.0.2
        restart: always
        environment:
            L2_PROVIDER_URL: "$L2_PROVIDER_URL"
            L2_RESOLVER_ADDRESS: "$L2_RESOLVER_ADDRESS"
        ports:
            - "8887:8887"

    ccip-resolver:
        image: dm3org/ccip-resolver:v0.0.5
        restart: always
        environment:
            CONFIG: |
                {
                  "0xafb5b5032d920c8158e541c6326ce63baf60aabf": {
                    "type": "optimism-bedrock",
                    "handlerUrl": "http://ens-data-source:8887",
                    "l1ProviderUrl": "$L1_PROVIDER_URL",
                    "l2ProviderUrl": "$L2_PROVIDER_URL",
                    "l1chainId": "5",
                    "l2chainId": "420"
                  }
                }
        ports:
            - "8081:8081"
