version: "3.6"

services:
  ens-data-source:
    image: ens_bedrock_resolver:latest
    restart: always
    environment:
      L2_PROVIDER_URL: "$L2_PROVIDER_URL"
      L2_RESOLVER_ADDRESS: "$L2_RESOLVER_ADDRESS"
    ports: 
      - "8887:8887"           

  ccip-resolver:
    image: ccip-resolver:latest
    restart: always
    environment:
      CONFIG: |
        {
          "0x410ebbabb4471e9c18cc36642f4057812e125e94": {
            "type": "optimism-bedrock",
            "handlerUrl": "http://ens-data-source:8887",
            "l1ProviderUrl": "$L1_PROVIDER_URL",
            "l2ProviderUrl": "$L2_PROVIDER_URL",
            "l1chainId": "5",
            "l2chainId": "420"
          }
        }
    ports:
      - "8081:8081"
