version: "3.6"

services:
  ccip-resolver:
    image: ccip-resolver:latest
    restart: always
    environment:
          SIGNER_PRIVATE_KEY: ${SIGNER_PRIVATE_KEY}
          CONFIG: '{"0x410ebbabb4471e9c18cc36642f4057812e125e94":{"type":"signing","handlerUrl":"http://host.docker.internal:8887"}}'
        # CONFIG: '{"0x410ebbabb4471e9c18cc36642f4057812e125e94":{"type":"optimism-bedrock","handlerUrl":"http://localhost:8887","l1ProviderUrl":"https://eth-goerli.g.alchemy.com/v2/XsX8NB_NvPFNUIAPQmOSjP4rMqsrTGDV","l2ProviderUrl":"https://goerli.optimism.io","l1chainId":"5","l2chainId":"420"}}'
    ports:
    - "8081:8081"
        


