version: "3.6"

services:
  ens-data-source:
    image: ens_bedrock_resolver:latest
    restart: always
    environment:
      RPC_URL: "https://goerli.optimism.io"
      L2_RESOLVER_ADDRESS: "0x39Dc8A3A607970FA9F417D284E958D4cA69296C8"
    ports: 
      - "8887:8887"           

  ccip-resolver:
    image: ccip-resolver:latest
    restart: always
    environment:
      SIGNER_PRIVATE_KEY: ${SIGNER_PRIVATE_KEY} 
      CONFIG: |
        {
          "0x410ebbabb4471e9c18cc36642f4057812e125e94": {
            "type": "optimism-bedrock",
            "handlerUrl": "http://ens-data-source:8887",
            "l1ProviderUrl": "https://eth-goerli.g.alchemy.com/v2/XsX8NB_NvPFNUIAPQmOSjP4rMqsrTGDV",
            "l2ProviderUrl": "https://goerli.optimism.io",
            "l1chainId": "5",
            "l2chainId": "420"
          }
        }
    ports:
      - "8081:8081"
